# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DiagnosisView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for boilerplate
  pod 'Fabric', '~> 1.7.7'
  pod 'Crashlytics', '~> 3.10.2'
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'

#  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


 post_install do |installer|
     # REMOVE ALL WEB VIEWS
      react_project = Xcodeproj::Project.open("../node_modules/react-native/React/React.xcodeproj")
      react_project.main_group["React/Views"].files.each do |file|

         if file.path.match(/^RCTWebView/)
            file.remove_from_project
         end

       end
       react_project.save
        ## Fix for XCode 12.5
        find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
        "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
        find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
            "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
 end

 def find_and_replace(dir, findstr, replacestr)
   Dir[dir].each do |name|
       text = File.read(name)
       replace = text.gsub(findstr,replacestr)
       if text != replace
           puts "Fix: " + name
           File.open(name, "w") { |file| file.puts replace }
           STDOUT.flush
       end
   end
   Dir[dir + '*/'].each(&method(:find_and_replace))
 end
end
